### ISSUE TITLE
catchesT and failure messages

### ISSUE THREAD

**Issue by roboguy13** [ku-fpg/kure#2]
Would it make sense to have a combinator like `catchesT` that aggregates all the fail messages if everything fails? As it stands, if everything in a `catchesT` call fails, the only failure message is `catchesT failed`.

Maybe it would make sense to have a combinator like `(<+)` except that it concatenates the `fail` messages together if both arguments fail?

A (potential) use case for this could be a solution to ku-fpg/hermit-shell#23.

**Comment by roboguy13** [comment]
One thing that I noticed is that, when I tried this change out, I end up with a lot of messages that say `there is no child matching the crumb.` in addition to the error messages that I'm looking for. I can filter those out, but maybe there is a better solution?

**Comment by Sculthorpen** [comment]
The problem here is that the Walker class provides an inefficient default definition of childL.  I suspect if we override it (in the Walker instances in HERMIT/Kure.hs), then we probably wouldn't get so many of those "no child" error messages.  (It should also be an efficiency gain.)  I don't have time to try this now, but I can give it a go at some later point unless you want to have a go?

**Comment by roboguy13** [comment]
@Sculthorpen I would but, unfortunately, I don't feel like I understand the system well enough in order to figure out how to make that change. I'm not very familiar with that particular formulation of lenses and I'm not totally sure how `childL` should work.

Does the change to `(<+)` in KURE sound ok though?

**Comment by Sculthorpen** [comment]
Yes, I think so.  Although I wouldn't format the message with a "\n" character.  As now we can get a tree of error messages.  I'd suggest:

"(" ++ s1 ++ " <+ " ++ s2 ++ ")"
